server:
  port: 8090
application:
  formatted-version: 1.0.0
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

   #H2 Database 配置
#   driver-class-name: org.h2.Driver
#   url: jdbc:h2:file:~/.homemaking/db/homemaking
#   username: admin
#   password: 123456
#  h2:
#   console:
#     settings:
#       web-allow-others: true
#     path: /h2-console
#     enabled: true

    # MySQL 配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homemaking?useUnicode=yes&characterEncoding=UTF-8&useInformationSchema=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health']
logging:
  level:
    com.evan.homemaking: DEBUG
  file: ${user.home}/.homemaking/logs
