server:
  port: 8090
application:
  formatted-version: 1.0.0
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homemaking?useUnicode=yes&characterEncoding=UTF-8&useInformationSchema=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health']
logging:
  level:
    com.evan.homemaking: INFO
  file: ${user.home}/.homemaking/logs